# BEGIN CONFSH MANAGED BLOCK
function _csfBashProfile(){
    # u=rwx,g=rx,o=rx
    umask 0022
    # number of history
    export HISTSIZE=10000
    # golang
    export GOROOT=$HOME/local/go
    export GOPATH=$HOME/go
    export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
    # Change default EDITOR
    which vi > /dev/null && export EDITOR=$(which vi)
    which vim > /dev/null && export EDITOR=$(which vim) && view='vim -R'
}
_csfBashProfile
unset _csfBashProfile
# END CONFSH MANAGED BLOCK
